##
## STM32World 1st libopencm3 test
##
## Copyright (C) 2009 Uwe Hermann <uwe@hermann-uwe.de>
## Copyright (C) 2025 CurrentMakers <lth@currentmakers.com>
##

BINARY = blink1

LDSCRIPT = ../sl_mcu_f407.ld

include ../Makefile.include
